program: proofflow/train_gfn.py
name: sweeprl
method: grid
metric:
  goal: maximize
  name: validation/mean_reward_a
parameters:
  batch-size:
    values: [5]
  train-repeats:
    values: [5]
  num-tactics:
    value: 50
  temperature:
    value: 0.8
  load-checkpoint-path:
    value: bigmodel.pt
